const projects = [
  {
    title: "Игровой магазин",
    image: "../public/assets/img/portfolio/game-shop.png",
    description: "Игровой магазин",
    tools: ["ReactJs", "Tailwind css"],
    github: "https://github.com/klekwedge/game-shop",
    link: "#",
  },
  {
    title: "Портал Рик и Морти",
    image: "../public/assets/img/portfolio/rick-and-morty.png",
    description: "Портал Рик и Морти",
    tools: ["ReactJs", "Tailwind css"],
    github: "https://github.com/klekwedge/rick-and-morty",
    link: "#",
  },
  {
    title: "Приложение Todo",
    image: "../public/assets/img/portfolio/todo.png",
    description: "Приложение Todo",
    tools: ["ReactJs", "Tailwind css"],
    github: "https://github.com/klekwedge/todo",
    link: "#",
  },
  {
    title: "Сайт-портфолио фотографа",
    image: "../public/assets/img/portfolio/photographer-portfolio.png",
    description: "Сайт-портфолио фотографа",
    tools: ["ReactJs", "Tailwind css"],
    github: "https://github.com/klekwedge/rs-projects/tree/photographer-portfolio",
    link: "#",
  },
  {
    title: "Simetra",
    image: "../public/assets/img/portfolio/simetra.png",
    description: "Simetra",
    tools: ["ReactJs", "Tailwind css"],
    github: "https://github.com/denisstrizhkin/simetra",
    link: "#",
  },
  {
    title: "Фильмы",
    image: "../public/assets/img/portfolio/movie-app.png",
    description: "Фильмы",
    tools: ["ReactJs", "Tailwind css"],
    github: "https://github.com/klekwedge/rs-projects/tree/js30-2.3-movie-app",
    link: "#",
  },
  {
    title: "Галерея фотографий",
    image: "../public/assets/img/portfolio/image-galery.png",
    description: "Галерея фотографий",
    tools: ["ReactJs", "Tailwind css"],
    github: "https://github.com/klekwedge/rs-projects/tree/js30-2.2-image-galery",
    link: "#",
  },
  {
    title: "Игра на запоминание",
    image: "../public/assets/img/portfolio/memory-game.png",
    description: "Игра на запоминание",
    tools: ["ReactJs", "Tailwind css"],
    github: "https://github.com/klekwedge/rs-projects/tree/js30-3.2-memory-game#",
    link: "#",
  },
  {
    title: "Видеоплеер",
    image: "../public/assets/img/portfolio/custom-video.png",
    description: "Видеоплеер",
    tools: ["ReactJs", "Tailwind css"],
    github: "https://github.com/klekwedge/rs-projects/tree/js30-1.3-custom-video",
    link: "#",
  },
  {
    title: "Аудиоплеер",
    image: "../public/assets/img/portfolio/audio-player.png",
    description: "Аудиоплеер",
    tools: ["ReactJs", "Tailwind css"],
    github: "https://github.com/klekwedge/rs-projects/tree/js30-1.2-audio-player",
    link: "#",
  },
  {
    title: "Математика для детей",
    image: "../public/assets/img/portfolio/math-for-kids.png",
    description: "Математика для детей",
    tools: ["ReactJs", "Tailwind css"],
    github: "https://github.com/klekwedge/math-for-kids",
    link: "#",
  },
  {
    title: "Математический калькулятор",
    image: "../public/assets/img/portfolio/math-calculator.png",
    description: "Математический калькулятор",
    tools: ["ReactJs", "Tailwind css"],
    github: "https://github.com/klekwedge/math-calculator",
    link: "#",
  },
  {
    title: "CSS слайдер",
    image: "../public/assets/img/portfolio/css-slider.png",
    description: "CSS слайдер",
    tools: ["ReactJs", "Tailwind css"],
    github: "#",
    link: "#",
  },
  {
    title: "Лендинг «Cuda»",
    image: "../public/assets/img/portfolio/cuda.png",
    description: "Лендинг «Cuda»",
    tools: ["ReactJs", "Tailwind css"],
    github: "https://github.com/klekwedge/cuda",
    link: "#",
  },
  {
    title: "Лендинг «Decor color expert»",
    image: "../public/assets/img/portfolio/decor-color-expert.png",
    description: "Лендинг «Decor color expert»",
    tools: ["ReactJs", "Tailwind css"],
    github: "https://github.com/klekwedge/decor-color-expert",
    link: "#",
  },
];

export default projects;
