const projects = [
  {
    title: "Игровой магазин",
    image: "../public/assets/img/portfolio/game-shop.png",
    description: "Игровой магазин",
    tools: ["ReactJs", "Tailwind css"],
    github: "#",
    link: "#",
  },
  {
    title: "Портал Рик и Морти",
    image: "../public/assets/img/portfolio/rick-and-morty.png",
    description: "Портал Рик и Морти",
    tools: ["ReactJs", "Tailwind css"],
    github: "#",
    link: "#",
  },
  {
    title: "Приложение Todo",
    image: "../public/assets/img/portfolio/todo.png",
    description: "Приложение Todo",
    tools: ["ReactJs", "Tailwind css"],
    github: "#",
    link: "#",
  },
  {
    title: "Сайт-портфолио фотографа",
    image: "../public/assets/img/portfolio/photographer-portfolio.png",
    description: "Сайт-портфолио фотографа",
    tools: ["ReactJs", "Tailwind css"],
    github: "#",
    link: "#",
  },
  {
    title: "Simetra",
    image: "../public/assets/img/portfolio/simetra.png",
    description: "Simetra",
    tools: ["ReactJs", "Tailwind css"],
    github: "#",
    link: "#",
  },
  {
    title: "Фильмы",
    image: "../public/assets/img/portfolio/movie-app.png",
    description: "Фильмы",
    tools: ["ReactJs", "Tailwind css"],
    github: "#",
    link: "#",
  },
  {
    title: "Галерея фотографий",
    image: "../public/assets/img/portfolio/image-galery.png",
    description: "Галерея фотографий",
    tools: ["ReactJs", "Tailwind css"],
    github: "#",
    link: "#",
  },
  {
    title: "Игра на запоминание",
    image: "../public/assets/img/portfolio/memory-game.png",
    description: "Игра на запоминание",
    tools: ["ReactJs", "Tailwind css"],
    github: "#",
    link: "#",
  },
  {
    title: "Видеоплеер",
    image: "../public/assets/img/portfolio/custom-video.png",
    description: "Видеоплеер",
    tools: ["ReactJs", "Tailwind css"],
    github: "#",
    link: "#",
  },
  {
    title: "Аудиоплеер",
    image: "../public/assets/img/portfolio/audio-player.png",
    description: "Аудиоплеер",
    tools: ["ReactJs", "Tailwind css"],
    github: "#",
    link: "#",
  },
  {
    title: "Математика для детей",
    image: "../public/assets/img/portfolio/math-for-kids.png",
    description: "Математика для детей",
    tools: ["ReactJs", "Tailwind css"],
    github: "#",
    link: "#",
  },
  {
    title: "Счетчик калорий",
    image: "../public/assets/img/portfolio/calorie-counter.png",
    description: "Счетчик калорий",
    tools: ["ReactJs", "Tailwind css"],
    github: "#",
    link: "#",
  },
  {
    title: "Математический калькулятор",
    image: "../public/assets/img/portfolio/math-calculator.png",
    description: "Математический калькулятор",
    tools: ["ReactJs", "Tailwind css"],
    github: "#",
    link: "#",
  },
  {
    title: "CSS слайдер",
    image: "../public/assets/img/portfolio/css-slider.png",
    description: "CSS слайдер",
    tools: ["ReactJs", "Tailwind css"],
    github: "#",
    link: "#",
  },
  {
    title: "Лендинг «Cuda»",
    image: "../public/assets/img/portfolio/cuda.png",
    description: "Лендинг «Cuda»",
    tools: ["ReactJs", "Tailwind css"],
    github: "#",
    link: "#",
  },
  {
    title: "Лендинг «Decor color expert»",
    image: "../public/assets/img/portfolio/decor-color-expert.png",
    description: "Лендинг «Decor color expert»",
    tools: ["ReactJs", "Tailwind css"],
    github: "#",
    link: "#",
  },
];

export default projects;
